
workflows:
  default-workflow: &baseline
    name: Main Workflow
    environment:
      vars:
        CM_KEYSTORE: Encrypted(Z0FBQUFBQmV0R3B4ZEVUa0xJSUNWS2FuaHZPRUdmTURXS1FWQXNxNEM3UkFlVWdzUmh1amtFMnpTMDJOWTlPZ19iV3B6WEYtYnZtdmpiZ1hUTXdMWG1kQ2dtYl92SUdfTW5Xd3F6NEFGOFp3QWh3MzBTTjB3dm9nX1V4ZHphaDNpWExWZjlNMUVVcENJOFJCTlVtOEI4bk53Q1dkZGJIU2dBSVdFYVh1MlUwYWdmR2tfVnNKRTZ3cjduWFJ4NTVXNmhoaVhaWUgxUDdJT0pITlhteTJqS04wR293WU8tMW9DandxcFAteGRBNnd0dEY4TmkwalFHRVZkWER5cjFiVGhHLW5mbUtmNDFLV2ZrbHBKbDdSYTZkWE93UURXT3c3ZkpQZjlwYVFiV3JmVDdGc2RrMlJTczVuUjhack55ZGtKM2pEUnBJMzRhUkZVTldzWm53bXpuQTVVNkk2dUpTLVZSWTJJMnU2d1N2WDM0WU1tYVd3SXN6SEZGMjRKVXNNV09hTzIyNmphc0FTbzdiX3RTd1NMR29OWXB2aTNfZFgxN056UGdaaFN5cXQ1aXJlLXpDSUp2TkdmaHBWUmo4dEU1SXhIWmxVMWlYc3R2bFYzdXFleVBpeThkdEF1VDBkbVVrdVNYZVgtUFdrSHdDWWQ0MTNRRUFyRlhRQnRheF9mNk02cklYdjYxSzFiSHZ4UWFKWE1GV0RWeVJUQjc5RnJvSWxXQ2JCcVNIR0RuaDVsZlBRaFotdHBXbXAwYTBYX1ZpME1HcHlwLVMwdHRJTGI1UmRjcTlzbEVCODRNcjZQaXZfSXZ1TW1GS2tZVkQ2UUJnOWFLSjFjMHg5Q0RSSVRZbklUZ3pYVUV4T1lVTEhMeDdZekhrUnUtdHZabmRqMk9aeGszbnhhenZGV01VT1l0TF9GX2wya1pyUHQtdU80VWlfQWlaYmhfY3d5ZkctS3NCdnFscTZmT01ITG9iTTlXSjNFVkRZTHNQdDBIQjFTRmIzQ2dUTEZ1YVlzYWJ3dEg0OW1rbUFGbzJQS2ZFTVQ2cE9NWDJOYTVvaGl6RmhIWTViTWxWbWFsOWZoM1dFR0Jab3N0TE9EaGpVa043UkdkSnlyOC10d0tpMW8tRVBUTDY0cWR6RDFNbWNzYmEzbXFsbF9XQnAwRUNjNGVYaXZYXzAzdzRNdk1fOTFiNy1jYk9rRWFEM01KMUMtNm5EelhNWk15ODNVd1hkV2xnYUhwY1VGcGN0YV9wRTRIVzFtblk3cFgwTkQ0aHd5TThWR0p4LTRKOHBray1mTTZncWJSWmRTSlJqV2VwdU1Tam41eW1QWjJ4aG4yOVRrY2JjWDdGT2QtOFN2Qm1PWDVVOXVXM1drR205Q05Fb0pqWDBCTFBCZWNHZTF1eFZ3TkxMSlBMcDdzbmI5VUdHSDVnRm9zT0FIV3g3czhEZVFiYklKMHYyOU1vN0tIVFVtV0lmcXI4U0hnWnAzX1VEVTlRNVRUOHNBb0lkM2hYMURuZXAwTmdKVW45YWdmZEZleS1RY1J2a1dZN1NCSXN5czlFeUJBR1VPVmhWZ1RYaER6SHZ4WjlUZFBjX2V5MmRlT3Z5aXpRenExX1hGamJiVkFPZHdXVC1IZzVEdGxvei10OXUtT0t4cG9tYk0tbzVBanhCclpSYmxWeG1uR1hscHlHdUdOa0JGWldPZjVDWXJ3dFZGSmFqZUFkS1VjV2wxQTluTGx0d2l3LVFBRzc1djg5N3pFbVRzRGFwZnAxbnJuX0NScVBJU3NIemZCbFNzd2pDMHVERXI1dEJGbUxoQVQxZzUwUWlPcjh2S3gzTWRNWWNnOTNKMXlOLXhOSm1MNDFrMVdTU2k1ZmRzRktIWFhYTzVzdlZjbnpodE53LVlLM19FdlhTMHVtTm9vaVBaNE0wTGZTblJNTnZaUWxnNjBLQlJSMDY0MlNZVk9sTkhHMk94NUVoNjZOYUxubWNVQlIyVTBDbExQVExvd2JhZE9JUTV2YUprXzZwSnlMWjVXYWxzODVveTBfaXJFVGZyWGZtV0NDQU1raUJESC1nMnBKblFjNlJjZVFhVE5ERWRfQVd0dm5IMWhtdVgyeWNjRmNDc1NKMWxnSXFDNzdjd3BJNE9PU0VaaG1Pc0pkVzhtOUpqcDFwTmFyUWVEX0dpYlN0RDhSd2RjYUhhQi1JdWotRzVGSm5yaEs1ZG5TSTA1cjR6anRpMHRsZWoydG1uRGdOeEFCOEFJWVYwR2FPcXprckJkdC1zVG01bHhXS0FTU1ozVXZRbHNyZW80dnowUWk3LWtTNkw4N2liMHU2QVVPNVI3RGVLaUJUWkZOWlZOVDBWTnRYQ05PcC1idEYtOG9TLXVxdnV6azJRbnE5aGZFdGNod0thblQ1X3RWUXRnWEpWMGtweW1UdEY5ZFNMT055YW1vXzNfekwyTFhXcDR1OHRydlNqeV9nUV81c3l0enEyb3paNVdiSHlsQW80a0hoSVdzRENHVl9IWlFzejRjRENlMEkySkF3enVJM2czbHpuRjNOYVpWbC1PVmRhMXVVSHZKYlZRVDZabVQwTEc0QkpIZkk0aUJPVWJEWWRzSXJjSWdUS0xYUUtyeDRjaHdxQS1LamN2a2NlSFRkT0k4bWh5b2t1UFhUbTF6b2xvWE90eXkzS3UzMm90NnA2MmRUT19lZy00X3Jib3RoSjZMNGVtdl9ObDVud1F6M2VsOXNrY3ZpSHBsN2dEbkd2SUY5bmtKM1U2NjI0blpxa2oxbEFIbVJkZkd3aVkyQWNvSkRlSTN1ZGVyZnhiWjBYOUJjLS1OYTlHSzZUZHpydG5fclU1RlJ6VUxVUTFNeC1Ud1IxUU9CZUF6R09UM3dsX3l3WDk0V3Eza0l5NjRwYVN5NDRIWHBBR0ZMV1RvcC1faDBJSXhxVW1xWTM0c0JHZkNka3pOa0h0dDh5M0ctX1h3cFo3dXF2bXpEbXJUN2RYWHhRbW9fZnNfX3lSYkFnWERxYjVsbVVValRaR3dPazQtNlNwZVR1Yk9OWHc3SVVCZDZCbzlqY3FNd3UxNDlaczBnSEduQ0ZkcXNMQzVTNTVKWG50QTkzLVNEVldqMUpnazdXLTlQWHJWYzlmVHloZFJkTlNqTEZfNW1falVXSGhmb21WTnM2Z1ZGT3FjU1VBZDdVdVA5MFhGUERCQU5QdmtRcXVnNHBEY2hON3c3bzdXWldud2g1MnoxTzhsakRkeDN3X2dJeXZBUXZxTEJObktSc1dXc0Mwb294NnJ4dFVwU283S25WU1FuSDhhZmtJbzh4ZFhWbUNlV3ZhcFVUNnVPTS01cHFEOTBZazFrZzNnTVBBTDVGV0ZxanRDY08wUnJpNGluOVJRSWJEWlMyMndFcVB3dmVfeWtqWUxYMlozelpzMDlRSzh5N1RBUFRYSG52QUNTWWpHYl9XS1FMbG1KNE9fTEwyLWhpRmVsR0hmZmVMRnlKQXdNS0UxT21oLXpRVHFwR3RPdm5HNXptMzFla3l2RzE3MG1XQUhoV2FoNmU1NGRSR1RjN0h5LXpHTUlQZzRINlQ5dTZDOVhyWkFxbFZMcWpSQ3VPZnhFXzl4UDZWRTlkLVM4MnBOeUN3LUtFUmRsay03LTVNRFdxXzgxdEpGUGFtNzV6bUFfOHRIcDd3ajRicUk5UXA4M3VqTW9lZnMwWlFlNGtmYTVVMXhuZUVaQnctdUVuX0w1a3VUc3I5WUhsUURGQ3pXVHdXdENwa2hHRC1sUmdRTlpSX3FyWDhDSlNiODhISDhIRjZRRURUTkNONXh1Q0NLaUpKaUtNTzlmZ2FOTjJUVUtTeHlPcFRMR0prcERDMUJmS1JNWFdKZjlhMF82UWtQbGpFUTFjNVpQdUZ2VENxUk1ZZE5IZnFaZGMzbUlPdENGczJ6UXNuY0tZaFBsSkxXQUJxRzRNYmh0OU9DNXJSZmF5Zzg1a2tDdkRTZ09yUFBEalpaSS1faGdtVFROc1ZQRFMtN2tyTDZMOE43NVFMaG5rTnV2a2VGVW1yU2llZ0FLSDZDbHNrQWx3dGdkekcyWkExNjZ6N3dpZG1ZNUVFMFB0M2ZfNURONVhSYnhkaUlTX1FVOUJwcVF1N1ctcW1zeVdQTDJfSGZaTG1SWWhyeGE2cGpOams5czZ2WW4xbXFMNUdhdHc2SDlFVUNoNWxmTHl3ZmVBWUhpaDh6cTkweHJsQ0JJZFlVN2FUX2dlY1dIUDUxV2ZMUjB1Ql9yR21sR2dsNFRkeUlrYU9idXpsMU1pTmxFbDlnVmFlZFBIamJsbVZyR3hHNmlXaUFZV2d3bkNwU3B2NDExSk9tWkxnRHIxNjBNcWZ0SWp4SWtnNkU4eTdENzhIbEd6ZTZ0WjAzRUFYRjFTMmJidE9qX1d2eGR5M2FhSjdxSzc0TDFkczk1MTVXX2VDQ193ejRUcW8wZkdmQjlYOFMxcGFzZGRORk5fdEdfMjVKdnZsTDNoeXNIYUVZTUlHQm10NzN0NV9IaDlJV2RxMkFxX0V0LVRGY1NrZDhMV2hnTnpJQjV2NWN3REx1VG84SklGbVZvZENUb1NmT0hPSWozcmxJQUVjRTN3ZFJWV3I0UHQzMVNsUzRMQ18ydkpTWmVqbXdLT1hNQXNXQlg2em9GTmZFX1VlWTlBM21SXy1aVl9wSVVybUNDX3RoLW5ScUFRMmpSdWQzRjVwbmJHcHhzakVaR0FOUEc4dTVRTzFvZkVFd0hqdnI5MnBkaHBiLWI1RnU2bWZWV0YwbW1iX1c5VHp1eGVPcFd6Y0Y4SFd4Smp5WlZnWjdzWUk0dlh2ajJuMmlJUzZsd01DcUdHZDhGWllvM0kzTUFtMmZyTW5yVTk2VmNRLU1LY3ZDUzFuTjNEQlNMNWd3aVlKWXE4QzRMZGRIc0tueElGVXVua2RvaVBBdDQ5WEhqaGVGV05sMUs3VzQ3cXlEcjduMlFjVk42NUFVOUU5dzhZMG9qbHAyWnJReGpYckhqbmp6TFh6VlZwWGhmTGdEWUR1STViNVNyVnllUENSdXlLQ3loYmlCX0t1dXgzR3M3Sk1NeE5rLWl1cnFUU2tfZ01nVERGSXh3YjZiN1dCbXNLMHFsUDdfbUtiZ1MyWV92WjZnSUJTMFNBMF82RE5rVGpXcm1tLWo4NVUwTG5SN1RmT2ZNRjI4RU1RaTNHY1BFa2pJTkNlQmFldW1wX0hfakd3ZjZUdWtpVTlMdFRYdzR1VmVqa200UTM0dTBGQzZJaHppemNlSkhvUGtPazFtU1NTY1NkcEQzaVJSZUp4YnZaLUNSeUR6QkdoRFBuQU83WXR2SWFiMDF1djB2VGtDZWFWQUp2dE5ZQ215Y3l3a3dkQmNIemVqc3BCRmRKTXNsbHNJa2l1M2U4SDlRWHR4bTJjQ3pjTWNoX1NVRk4wNGFaMXRMZTV2bFhRMD0=)
        CM_KEYSTORE_PASSWORD: Encrypted(Z0FBQUFBQmV0R3B4NVhQMVFheGVGbFJNQWFxTWg2LVlkckVnaWRjOU83cTEtbFBBSzdzVVF0MGNOc0xPSFpDTl9LSEZQTXUzajNWaWxXZ28wSG5Wak9vWEFhZzRMTVRHNEE9PQ==)
        CM_KEY_ALIAS_PASSWORD: Encrypted(Z0FBQUFBQmV0R3B4alZrZlEtRUE1Xzk4T0xyWno5cHdyNjFSUDBJX1haUGFUVnZRUWtwaWV5Zmp5VHp0bVRKeUVzX1kzRy00QnlRR1lYWjhrRHNNM3lpZDNGRXNiRW8wNmc9PQ==)
        CM_KEY_ALIAS_USERNAME: Encrypted(Z0FBQUFBQmV0R3B4MEZreVJMWHFQMXdmSjMzemFiSklBX255NTcyc3IyRktjUlhuZldxZF9xSnpaOFZFVzZlazFtN0hVVUdPQVNNWUdZT0QzQmpMX1NzQ29KU3E4TzZFQlE9PQ==)
      flutter: stable
      xcode: latest
      cocoapods: default
    cache:
      cache_paths: []
    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: '*'
          include: true
          source: true
    scripts:
      - |
        # set up key.properties
        echo $CM_KEYSTORE | base64 --decode > /tmp/keystore.keystore
        cat >> "$FCI_BUILD_DIR/android/key.properties" <<EOF
        storePassword=$CM_KEYSTORE_PASSWORD
        keyPassword=$CM_KEY_ALIAS_PASSWORD
        keyAlias=$CM_KEY_ALIAS_USERNAME
        storeFile=/tmp/keystore.keystore
        EOF
      - |
        # set up local properties
        echo "flutter.sdk=$HOME/programs/flutter" > "$FCI_BUILD_DIR/android/local.properties"
      - flutter packages pub get
      - flutter test
      - flutter build apk --split-per-abi
      - flutter build appbundle --release
      - |
        # generate signed universal apk with user specified keys
        universal-apk generate \
          --ks /tmp/keystore.keystore \
          --ks-pass $CM_KEYSTORE_PASSWORD \
          --ks-key-alias $CM_KEY_ALIAS_USERNAME \
          --key-pass $CM_KEY_ALIAS_PASSWORD \
          --pattern 'build/**/outputs/**/*.aab'
      - find . -name "Podfile" -execdir pod install \;
      - flutter build ios --release --no-codesign
    artifacts:
      - build/**/outputs/**/*.apk
      - build/**/outputs/**/*.aab
      - build/**/outputs/**/mapping.txt
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      slack:
        channel: '#flutter_build'
        notify_on_build_start: true
      email:
        recipients:
          - ezeugwagerrard@gmail.com

  stable-workflow:
    <<: *baseline
    environment:
      flutter: beta