
workflows:
  android-workflow:
    name: Android Workflow
    max_build_duration: 60
    environment:
      vars:
        CM_KEYSTORE: Encrypted(Z0FBQUFBQmV0VTBpWFBwUmt4VjZuWjNnODluZVpCYU9PdG1fRzk4eXFSN005dWUtMWxDOGx5TS1MNDl6SHM1RjRQWVdURm42UWNwQnZBODhxOVB1U29ZSDJCVkFGX2NwTEdBczg1UmhURllzU0hvbE9CMzJweDI2bTEyVHFPNUtTS1J1dHViempwcEdjSTFSVU45Z29mN3dkcUNxclJ0MmNmV09VM2F5aHk1bjhfbzJtSkhwRmhvejlrX2ZuQWJYbExlTzFLc0JuM0VUcUNrUHkzWGF4V1VkR3d5TW9wcWVYbDRRQ1F0WVBxNWg4N1NMQmNLanlvemhxaE1DVUJLTlk4ZEs3eV9KSUtGV3A4SnE0NzZtUnUwZlRNZm95X3g4bm1ULWY3SEdQZHVrVnNzWXpOT19CZnhPUFQzVEt3cWRCNTR6YjB1OTBDNkZFTWVhdVZuT3F2V2k3dHN6bmhtdG1iY3VJMnpNVmhJT3RlZWYtcU1GM0FsYVJCYUdadVZKQ2hEQmVjaVh6Q0lXZjlHdzZGb2pUQUxueWV2S2tXUGk2TTNwMjlLM2JrTkZFTU9oRVdvMVFLN1hYOURDSzZiQWEzemFfdnB5SkJWMHBSM0RBY1V2cF91S3BBdzZ5VzhUSzJvN2lZV1dqeHN1N0hKTldVdHRyenBFeUt0M0VTMlZaT2lGS2Q5ZWROZTlfWEZRWjBfX1ZjNkZNWklSY2FCQjdwdlowMUJuRFgwVEQ1TmlkME5iekdSUFhXc2txZ0FMNHlERkR3Mnc4OG50N0Vka2ZVcDdnUmJ0a1F1R2pSdm9CMlUwSnB0VlFtM3BQUjFxWUp5YVI5VVlJb1hlX3lVeDhBUXhJc2kwSzdvMlFPblFoQnFsQnpXc2pWTkZJYnZDbW1tZm1ya041V1NmZGZ3ZnA1RGloV2hCRE5ub1VRMHRkOHhtTEVOcFdxSDBsSmlNLURRd2hLOUxPTUZPUFNjeVk5SHluUUFuYWhXc3NCbUMtQXRmbXgxSnowak5kYjdIZ29sNWhmSkkwbElaS3VJMTdiRkM5dXVITnJkNUFXUDJ0SERMcFExTko1TE9SZi16Rk9pV3QwVmw5bG5wNWRFd3lpQkFETXRCVzdsZ0dJRW9zTTh5LXdWNG5DXzA4QzhRVnZISjlEZHZHaUotVmhORi1WVmVrZlVWSXlxSkRhT003MjlDX3RBQjJwVzNvb1pXaDZ4T0c1MDVGa2hJcWN4N1lRbEJGX0ZWOUpnVnQ1U05lV0FzMWprOE9QSC1jTHRXM2JBTHdvX2pxRzlZb21FYkxTcDVzdEZJU2VrYWhBWU9qMldlNm95WkRrdnNyNmNnQWFrcjlqTkRDRzgyZzNkaDZvTnJmMXdqNWJWNS1EMEtmWW9FalJaVDNpc3g2MG5FUUFaRDM3WUNIT3FYYUJ0TERvV0tsOWZCN3VyZGJhTUdrNWRuRXBYenJxV3dHSkZJYlItSmJ6XzZUR2xBVW5BT2R4cHk5SGEtQVBxcm14STFjaHF5empKWmo1dnFDaW1FOENmLTR6bm9lVlJHTmJqdUhUMk81NTljQUs4Ym55bUgzWmJfdG1ZWHdaZmVCUTR0M2lJMnVxMmY3VDR3NXZuQ280bjFmcXRLMlB1UHZIVHhpejczVVNTTVl0aFhlN2JRN1RsVDdGVEFXOEZodmxoTzlxdktDTml4VEttMUlPam1tQUd4TnQ1dDZJSUtUbTduTWZJM3RNeVNIeUdiU0gxbHJJMktTTHZobllwbVNGTFEtRk9UdFNtSFZtY2pxMGxmckJvdU50aUlSUkN0WmRydmFicno3Sm40S3BTUms0dmRBZURQeU96cTdVZkJuYm9zR3BKWXhlalY2UTRfcEladXBGXzktYXNzTjV0eVBYRThPcWxtMGhjbE9oTUhQcjhRckt6MXdGQnFMYWVXOW1RMHlGT0U0WElHRGJZMFEtbjEtUGVaMC1jYWZDX3JOUjVRUkxSZjUwdmtHVlNzUmU0VGpGTXJkOXEwbnBwUjlxXzhLdlh2cXJjRDJQSV9Fb3VXUlpWVFNIeTBOdXQzTFpmQS1lQnMwallnT0p1WEd5bmhQdlBaMm1YV2xLR2Zja1U5T0tRQk1UZ1JKQnJmV19MUmpqczlWbGtsRmFQZmlQSkpwM1pDUTMtanBQaEtPc3ZYZFFoaUhoUFVZN3A1ZF85LUV4M1A2cnhGS0s4R0dSTE5MR1pxSWFFbkptNHE2cmVkSzRRZnpQaEwwN3djVWpJcVUyc1ZOcWtHcHZRX0VuNm10SF9LNVZEaHUtTzctUjFrTlJMaUxlMzNzcTFUVzdIN3RKcG1YVDh3TWZUUFFVUzVJNVkwVi1veVYyRF9JcTJhQkNya2ZkSk53dm9WYnhTYm5iRGRSZ0xGRkRyYWZDSmJYSllaaW1EbzZ5T1BjRXBVY1Y5R05iTFVZbWZMancwVVJmLUNQOWtCUWFOektOVGhHc3dCN0czZGJzX2V1QThucUFIMmptVEpEcTVEQ0RvYU8yMDl3WWtVcnFJNm50TmNuNWJ0MjQ1dnJHaWt3UnJiaTgySTFyTFM5bWhLU2RjREMwWjE0MVBZRERWN19fU0JyLWdRUmpsdThxWkhQemltSUdDUUJaNmxWRHJCbVctYjNuc2RZb2NSZFFOS0xFVGhFb0VHVzlaZzVfN0p0WExDSFZsdGRGMElDck9JcmZjLVJyTTg1YW1vYm54TzRsZGRfbXhFeEhGYjZTSXdScEluVW93WVBRUXBPTHVUMDJWbHlWWVpBZFVlb09OMXY0OGFsdUp5bDJEY0taUFJkSVBwUHFWYnhiYWRTX2ZnUzZqTWxlemJHU0NsajVoVGxOT1lCTXBtaGQ4RE8yTlJnWUJzNlpKdUU1bU52TmZ5X3JqVHNhV1RWX3FKVWVrTXFWQU15WHp6WURBQlhwLUM1Q0o4RGF6SWg0UDY0aFpFNElpaWFkWHBhb3ZCZER5SDI5dGEySGRPc0kyVDdQQk9uWWVGdnhmUEZoQnFSOHZpakx1SUsxU09zMHRoZTRFS21YbFFjWS00NjdxTmNHcEU0eldib0dwaTQxTGFKaWp4SnBMdGdkeXZYYkdUOS1EempoYTJZOGdObTZXWmhEbWNfbFFQUkZsN2l5TjBnZjlBa0dqOTRNOU94M3RzUHdLOW5aREEyLWlHVkxfRHE3N0hHOHFmS0VwcE5DZTgtQTRTTWtrVDczNkIwNmltTWRIaDZZc3V5dFAyVnRQRVplNWhDQmVfck83b2NWZGd4d2wxcUJxbktzLUtEQmV1REdJelFad0lpRk1vR19Qa1N1Nk5LVWpSZnp0OV9KT0QtcUZKQUpYY0FPMzJfaDhWTDM3ZUowdkdueDVTWkdnV3BnNE5DX0lJRkU0YjdNSVBZOEM4MHdzS2lUQk0zVVlIR19BMllSY05WYmg3czJCRzctWlJSY01qQnhiR0lqWXV2cGM2amh4SEtfcHlVWGQtYm93UkhzcGlWd2tVWjhqMXFsVW5FY1c5QjNJQlhaV3NJcEFFYkxwZVhCTjlHdmFKMHh6SUwtZWZJUDlfM2l4d0hzNm9LVWVuRUdqeGplMmtyR3M2TUc4Y29hVVR5MVpVT2FwZDZZalhwdU13UkFlbmVvajRmT1RLRXB5MnRMeG9BSG8xV1RsblZlbXB5aHBrcUhpcHVrUHJpcEJ0T0E2V3NLdzdLcTVicEZKTWFiWU5EWFE2U2ZqMS1NbWZZRnBJUlNkVFpHamh1d1pjdDZsaGNhYV8tRF9jSEt0M19MeTJQODRlV3ZNVmlrOFZPRmJMRnhQLUhkVWljTDNmNEpSNjBHczFGWFdUSnFPVkdETUJFaEFaRkVZLXVoQm9uTG9aZlhPejRzX2xQNlA1VHRpSklPQnhKU2otMUtCeS1fVWNZMEZaa19tMDlJTDJHUU1oeXFTSTk3aWVNc2FkenBNbi1hbjRVTTZMWEZPelRtVDZHX3JvMjNjcWxMeW9UMG45eG5lbVVTSDdVMTFRYWprOXBWTlc1MmpKdm9ob3FqaC04cnp0OXltYXdzUWJ4bGZ0d182c0llZXgyMVUxUzBnMDBGMDlNVHJvX19xcS1TU0FWY2FTVTMyMGxkOTBpbE5LLUc0dzM0R29yRWdhUnYxaURocElPRF9jU1EwUGJhNFp5YXhyUlpoVFlPcjdpc2JuVFJfQ2VNQkUzWVZVZ2NTZV9ZbXMyMkxxMHRBR2o0eXl6ak1GZl9HOC1GWU5XWVlEN1NRYTZMWTN0bWI0X25pU2Y2M0pWWU5jMXZyVFZoam5USWgwWnBLTS02VVQwZEE3TzFrTThyTFk2VW95aTdpcUQxTHdlano0dnE4UnVnQ056alRIS1JpU1FIWGZNekdualE1UFhJRnU4bkg4Q29UVXFmN0VzRklUbnBPdkdSTHJFS2RvOVZzVE1QamdRTDVJdVF5cmxoLXMxeGk5aktCNER1UzB4d3FDZHJNcnc4S3pTNlY4dHI0dHBGVmlDSS05U0ExSERPRjVNb1FSU1BrX3lBeHk4Ul9iZjBfMzBzdXB4YWthb1J3LTFOVDlCMlBjNjFDQ2RRdXk2OTdQZDVvbmlRRmJTZUI5bWVyemRfVzdXeWhYVFdoY1oxYUg3OTM5eUJUYmhMMUVjYm5tY3ZtSzVndExsaWxyeUZad0t0U25MZWJZNk9OX0RfbUFSbUJrUHBqLWxkbDQ0dEhBb21TQmhqM3pCOGNBR3I4b1VQRW4zZC1ZN1Nwa0lNYWZ6ZWhqVTBOQ0VKQlBhR1o5b1B6dWU5d21tUVMyZm9TOHVMR1dQR3JEbzhFTFRxSk44c1p2b1dIdEpjOUVoZUEyeG5LbFVhNkp4WUs0R2VJeUhoWmZXN1pWZFVSVUNOWndfM0kyXzBuekY4WDFVVTktRGNfNW1mZk9PcGJjc0hjakxsX2Z0bEpPbnBNZnpRX0dFMFBuek80N3ZRRVBocF9QT1ltbVFIZXRvS0ZpamJlTWhnWER3dlJOaUdXc3ZCUEZLSnFYN0Q4TXg5czdrRzZORWF5SzN6OWZjTkg2bGswUW5VcU82LU1rLXI3QUc4elV2aFN6TGRpVlJfZDBSMXVhQW5GU0k1cmhNNXViSmdQcXNva2pjdl9yNi1oS2pVT0V1VTNZZlFfWnhhOWRQbmpYTldiTl9zRmwxZUQyWGdzRkhSU1RCZnN6Wkdjc05zbzU0MUVaUEFBbDk2R01ZWnNUaS1hWmtuT3RxRHlFbTRzdHdTZTJ2YWU2Ymc3VHBIb0lNNDZveEtLVDIydlhVVi1LZXF0LUdDR2FVa0t3U25kM0dwOVMzbWxGcTZBV2xGd1Q3dFZBejZlOW5TWDZQSTFNSEFZSU4xRWtaUnRZUDl1QzdDMko5YVlTUXN6dTR3Y096UC0wLTBuUHJHaHlPbDRUb0Q5bVpUdm4xZGV5cXUwUWxCdz0=)
        CM_KEYSTORE_PASSWORD: Encrypted(Z0FBQUFBQmV0VTBpTUllMHVreXplRWRYc3JWeG8zOUFPN0g5R0lLbDlyVDZmSTlrbDc4R3NhVDZsZ09pMVo5NlBiOUJ3ajFQdUJfLWpTMDUycENzYXltWGk4Q0Zqd2tOZFE9PQ==)
        CM_KEY_ALIAS_PASSWORD: Encrypted(Z0FBQUFBQmV0VTBpVTNxY2ZLQjR3TWhWb0I3N0xJT0FpRUdJZEJmT1R3ZkxIN2lPSGprVkM1MnBnZ0gxdDFhWjJMajktRUR0XzFwQ1Y0eEZpQ29xZWd3MWcxVEs3VnpLZ2c9PQ==)
        CM_KEY_ALIAS_USERNAME: Encrypted(Z0FBQUFBQmV0VTBpLW1yMm5MSDFGWllBbmh4R0dWek4wUExMT1FGaUhtZUh1am45WnBWbmxyUEktd2NlcE9sMWY1alNxZWdLTzQwRlVTcFlSa1VwUDNkdVVpUnJsd0txLXc9PQ==)
      flutter: stable
      xcode: latest
      cocoapods: default
    cache:
      cache_paths: []
    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: '*'
          include: true
          source: true
    scripts:
      - |
        # set up key.properties
        echo $CM_KEYSTORE | base64 --decode > /tmp/keystore.keystore
        cat >> "$FCI_BUILD_DIR/android/key.properties" <<EOF
        storePassword=$CM_KEYSTORE_PASSWORD
        keyPassword=$CM_KEY_ALIAS_PASSWORD
        keyAlias=$CM_KEY_ALIAS_USERNAME
        storeFile=/tmp/keystore.keystore
        EOF
      - |
        # set up local properties
        echo "flutter.sdk=$HOME/programs/flutter" > "$FCI_BUILD_DIR/android/local.properties"
      - flutter packages pub get
      - flutter test
      - flutter build appbundle --release
      - |
        # generate signed universal apk with user specified keys
        universal-apk generate \
          --ks /tmp/keystore.keystore \
          --ks-pass $CM_KEYSTORE_PASSWORD \
          --ks-key-alias $CM_KEY_ALIAS_USERNAME \
          --key-pass $CM_KEY_ALIAS_PASSWORD \
          --pattern 'build/**/outputs/**/*.aab'
    artifacts:
      - build/**/outputs/**/*.apk
      - build/**/outputs/**/*.aab
      - build/**/outputs/**/mapping.txt
      - flutter_drive.log
    publishing:
      slack:
        channel: '#flutter_build'
        notify_on_build_start: true
      email:
        recipients:
          - ''

  ios-workflow:
    name: IOS Workflow
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    cache:
      cache_paths: []
    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: '*'
          include: true
          source: true
    scripts:
      - flutter packages pub get
      - flutter test
      - find . -name "Podfile" -execdir pod install \;
      - flutter build ios --release --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      slack:
        channel: '#flutter_build'
        notify_on_build_start: true
      email:
        recipients:
          - ''
