
workflows:
  default-workflow: &baseline
    name: Default Workflow
    environment:
      vars:
        CM_KEYSTORE: Encrypted(Z0FBQUFBQmV0Qkg4OExlSTQ0cFZJb1B1bmFMMTctVG1BX1Y3WGhWZG01VmxWeXpscU50SjItSFdlZ0REWmpnSTFFREw4c00yc1pJWGlsR1ZPeHZMdlpDUGRqdDlxN3Q4b0s5XzRWOWliZ21sTTI5dDc0UXREeW5XR3RtMVJjYnI5Mms1bkp5cEVycFhYZ2ZQZFFSc0pjTG5oMFgxLXdGU2pnNkhMVjBKa3J2QlBxSnlacndhcmF6bEprU3lGYlZqdk40S0JBc0lIZ0M4NXEyRy1MQmx4Mld0MnhoR3NacmRvVXVFQmRQTnZxZVVETzE4Q3BfdURWWENnZzhNaUpOby0tRDNITDZOb2l0Z1ljYVhKdzJNbmtlVVVBTXV0ampUNUJaR0pTa2VNd2FwRVRQNVgtZV90U21CNFhzeWNjUlk5U2xqMDhocEdkUVRPNmN2ckhaWEhUeFBrYzRiSkVqTDNncVdzdmJaaVhqWURNWHZITnVxNWh2T0h1SXI2dThfQjNKWjJ0OEZOYWdQSnY5MC1tdldtU0xNUk1JOUIwU2pCTWN4NHlEaFpzYUFrZ1B6Y1FuVUpwSzBQMi00amFsLXZoWDFKNGEzUV90cWxSS05CRWNVOUllOGZjR2RvLXNYRXV4N1J2RTgtS3hCMUhxdkl2emRRUjJRbmtrUENudEluQllqZGYxMEh6bkM2LXdUejV0T2haVGI4Q09oVUNTSHNiSVdlcHNIT21IT3o3N0tiRjdZSW1BaExUbE5DTlQ5cG14MWNfZjNGLUsxcXhUSEZxbk5lMnlrcW9NRmNLbjVSOXZHWXl6Si1YZm5NcXhhbjFRY2RoYVA1U0pSTjBIU2xpY081NzlZOGszS0lLVGxDQ3BjM25fektEQWJLZ1ctUFFBdEpheGNuNmNzZldXd2E0WUQ1WkZmdGRYYktUOEVlNXNyTEtVdEtjS3hNekRzd1ZUWGlOSVF1WldCNnpxTzFucDhKeW5valdQam9GNmRuT2VwbUlwVVZyR3BHM2VncVB0SG51VU90MElRcXU3Y0lsRks1QzdSdVlhTG81UXJxODFHU21tbEF4RHAzOGU3ZzIxaEtCdEVucHMxaGNXNGw1Sl9fSFYySWtpX0RKbzFfSmJMOVZ0Q050azZUUzB3elNianR1V3Flc3JiRzZyN1FYNzZYZC1XdlBuMU9UM1U0ajdULWRCWjJQNDlWUFZwMEJfMlE4VUtkaHdYOER6VFB4TVBNUHBjTzVlTDBNTFBtQ0dHR05qeDV0T0J2MWtfTWcyazR1dUlHSGtYM2d4dURDblZMY0d1UGJvRVpNTVY2YWdoYkhPWXN2bzdWOXNLRHNpLTkzRGs3QzZ4OTNRbW5lMUZTSXdfb2R4MW5yeGlTaDJYaThNMnBodWhYUkFiTGt6MG9ReXMwVDlZWFRSWXdlQUFzYldiS01GUTY2OWdBSFpsYTltdkJqWktVOVlVOU4tSGZfM0JiUTYxbEZIUTh3SjlDdURqRXhPM19hbno4RUFEalBvcTM5dlUtQkJoblM5ZmxvWVZseC1MRDkwSTcxTUdCN3g0VnFNTEJ3eWViVDEzN2JfdUgwVXhDelktZkRvbTkwc0ktWEJDTXgzZVhKSlo1ZzBxelZVVTZhSlpWRnhRblpxWXZWc2poNUp1czdZaXU2Wm9oOFdnaVA0UXRRcTJnU3hVTDQwOVRmbHVVNzJxUkxEMDRVdmFvRGdJWjBHcHFod2RsSGUwZC1rcnZBempJMEw2QmFPN0ExRmNsLXpoalJqekdidG9jZWpvaV9ldDNoWVJYcjN1aEswVGtTSWVBb0cyRnctT005LWM0T1BuRlo5bkg0MG1laVFuZUpsa0hXUS1BV04zMXBOWFFXUHB0S3BOY21IM1pDRTB3ZDQ5LTE2Z3d2eEZjTFptcVRCb3pKWmtrdm1aWHRFd0tOQTJ4TElxQVhESGFCRlBKVllIbDhXOVdYLWJiZzMyOWp6UGRsRHN2b2QyMHZBa2FkaUhZR1JfaTVHU2R2RURuTDI3Z0tzOGZPM2trRTZXZDNJMGVhaWpFZlNfblZMX0txZkdNNElrNWVwd0JTSnFUeXVzc2publpzTlRqN2lsLWUzRDFhdldfUTZ1X2RQUUo3aGN4aW9jSkZPMUZvZUVIZ1pySVFpNE43d1RzVXNLSHFnQ1lFOHZDdnAyRFl4WmJEdmp0NW9hSHRvZG4xQThyV0VHSnpPZHNBd2FRcGJ4ZDVhUHRORVRPTjhxRGtEWGxEREJ1bXR5eWNZbUZZTW9NM21KYlpkTFN3djJZVXVoVDJ5VDl2Mk9GVEs3bno3cENJQlNFaklldnl4TTJGRHVKZXpLdFpZZ2RlTlJBa0J0MF9CVHlJWHpHc281dWxBS0Q5d1BwYWhyOGZuVS1hVFpvSVJsd0szMVpaRklCMGx1anliQU1qdGNHSkNlT3pYcUN6VDhKUndKQ2dGV3hLeno4SllmMW9JM0FDZHlhbEhvOWdFUlpyVVhOZ0R0bHpnNUhqUG5ZQTJhWGMwQVAtSlNNMmdJT2pUMzdWbTE0YXRuMjMxLUhhX3VIdlRpWjhKcGNjelJPRTNFS1RMMkVHWVNOR1JxWWNnamZ0M1FsT0pmN3V6ZlpONjdjakI0Ny1wZmszRVRqcE9RX3ZGOGpVUTBHaWdzV2F4c2VNOFoxRUlaSVd4ZjlxNUpTTFprQjdLUUNPRnk5dE9YTnRBUGN0T1BOcWtGNVZxM2pyZlRuVWYyZXRaSXFzM0I0VDdOSWFzcl9lSDVUREtsLTVmQTZQRm1yQnZSN2l0VTRSZlF1OUxrX0N2RXdMQ0NsRnhvNVM1ME5ZbFFWX3lfVGNpcnZTZFZlb2tjNXBUc0phM3RRMlRoVENKNDZGdWxlc0NYY1ZnWTlmTDBhcmJvQmItQlpLZWVRejhTMTgxZTVfQ2NUX1lpU0tkRlhCOU1sMFFheWIweTlGUGdPQjJlSjlScTZ0QXRaaUIybmFGTGs3bmxRaUpScDlhcnMtSUhnSlpEX3RIZ1ZMT0FSM09CRENTd3RqTGwtaW5CMnJneG50VldHWldER0hNU3M4ZGVOZFJMTE5WU2g1LWQwRjd6bWd4Z3hYclZsT2lrTG5RTDJDNThhTGV0NU9vMkZWRDVONlRCamtWSHp5RTc4TUFqWUp4WnFvQ3BCYk8zSEF0eU5hWFJLS3REbzI2R0haUTZnaExwaEpiWWg0M0VQdE5lR0tGUlVxamxpVjVFWE1uTS1CNnNHZkN1VjY1RkJFR281Q01Sb29JVVBYcHNjRkRXdWF2RGFYZmluLUR2cFQyQUh0YTlzWm84cVlJYTFSbXpEU2ZZRmpiaGxVd2VLN2VQYXp0UVhrY0NsUTkyQ3dWYm9scVVEYk9MTWV5RkRPSzk1bFlYUnFZM3M4SmM2UF9SQjlMQktBanVsLUNHSmVHREdNUy1ZLXFVWW8tdHRLQVMzQUtMR1VIemw1a1dxa2NtOWJyWXczX05UcHZNeHZfd2FsWTlFZjR6ajIydm84cGJibHpvWGYxX1NXZjhsb0Y4akFBTDV6NjBlU1hlRUR6aHdzc0N6alIwVWZhMzJMd0JobGtJdnExWVFsWmNqTExvazM4dGZkRGVLQVRuemlxMUxoWk9xVlh1ai1TUXNkS3pzTjZ5eDFUQUk4QUt4ZTFtLW8tMGtBc2lMZ2RXbXBwRWdBcExlRGhJR3J2cTJlaFpUVkt2VmJxeVN5dER4cUdRTlU0MTJxcEdJV2lmNWd4bUpFUnpWejFFWXZoZW1mckJFT3ByS0NpZjRRMWlpdnJDTlc0VG1GU3Y5V2VYMTRnV3pJVXVhN1BQZGlxc19jbGI3bUZlTWY1Q2xVbmNXTzVUSE0tYVBLS2cxRkJPaGNXVkRta0RfTXhqOEVWVU1jY2luMHZlNzlzSV9yQTVEZ1pOeEZvMnN5N3kyVWstWGtNVEZBNVRKdjFMYUdESTQxcjlLVkFtZWp4cUNMWWZLbTNDbktGXzZUS05oc0d1aWJKMG5XTUpHSDcwOHNIU1kxaDBIcHFESVR5QWJEYkdXTUZPcm1iTmlzYzhDYmltbzlYNVhiRmozMU9GTU54b2p4NXlRT0tKREF3dmtqb21ra2pLOFBTbHVNTEtsd211Um5jbURsUUlsN3RDTE1rQ2RGQ0NSaEF2TUJxTzhEdUY4cHhqY0hXQ3gzSkR4ZHBzdUhjTmRPM190ZHMwcmlRSnhLckV5VFJjYUcxREh0LWNLR3B2YjVCdHdIWnpJUG1XOEZYSlJ4RXc1V2JoeTQyZEN6N2NFRFdBRjJ3YVZnMkt3aEZVWUtRV0M4eDBhOEt5dldON0xaMWpfSGszNjZMcGpaTElCRDgtdmV4YVY3cnhjX21sZG5fYXVPeHBRdWlXWXZUUExDelJicElzMkRUWFYzVmpKblZZaEFicUh1MkFnT0dCbnZHVzhycm9YRVhlaHA5YWtyTXo3dUdnWlEzajJFZHZDSmVwcFBjQWxrZ2hVLXVMVW9MOTlfUnFVcEtPYldqdlUtOF9oX0IySERpTlRVQVk5c1JJNXNLNHBPR3hKbWphN0poeE9Gdzl3em43NTJjZXZ5ZnAyTXlNWE4yZ0tEYXFFMTVpWXVpWjUtbVgtbHBBOFI1RGVkc1MwU1BjWF9xb3ppTmdXeWVHOEpTSlVUc3J3SVhQQ09TS0pybFVlYlZDNnJlNjJDMWd3TXJUeXBySjA5MzY0NlRRWndCd3A5RHZ3a2VFOHowbUNMQVFXVG5MWjNzZVpYOERxem9jejJJYWZ2dFRTWnRwM01feEk1Uno2Sm1Tb3NjY0RscFJ3eDFka0g2NC1sblFuSzVWZ0lucUVoU2lkaVl3WEN5MlVlY1dtVlRJUS1hSDBZSktja1h1V1NORW85YzV2VmFQY1lXcGU2VFRIeUoyOE1UX3NfRXJaNmNDVDkyZ0FqSURSa1I2TEJUTXZwNVN1cE9VQU95R2xlZTFHQng4MlQ0MTk0OFRDYzdvN1BCaldXT20zMTZWdjV2cDVwem0xMEJJT1hKby1XN3ZYUTlRNFlCSTJVaTI5YmFLeFJnWFNPSE5Gc21RbXRyRnFVS2N0VmdFNC1wRzdEUTU0ZG5NV19fNjJPeFlQQ3FKTDVuRVVvQ3FZOTBSQV9ZN1hLZGRVdmpoQXl1Y1IxNnJuMU81R2h2MlUtc3V5X0xCMnZjRHZVOGFvOWtRTUR3dGVUWnRVX1drM3BfNGpiWnFmeEEwTGh4Yzl4eWMzTk9xWWtvRVdiSmFkNUlMZHAzQWVTczlSS3NaWTl0QkVRX1N4STFKRXQ0Mngzanpud0dBdFV5Tzc5cGdSMkZhMFRXWm56MnZjUmtTbXBNT3JrS1ZpdmdJZ013RHpRMHNYTWIxSXI2bzZiN2NzSmlTMUVuX09MU2IydktTNTFOTnl6MjFRTnBIR0dEdTRFND0=)
        CM_KEYSTORE_PASSWORD: Encrypted(Z0FBQUFBQmV0Qkg4NHMxblJRbUFBSXFNeWFtSlhtaU9VM1VkdGJuVDNCYlJPaHRyeDVBNDZxaUw4dU1CVkRPcWpSS1MyNkpxcW8ydXY4OG9raEFtdzlLMk0yOG9KS2dDVFE9PQ==)
        CM_KEY_ALIAS_PASSWORD: Encrypted(Z0FBQUFBQmV0Qkg4ZURlcndzMGFlcS1IaW1zVjVreUlPVTZvQ0FwRy1MenFKRjhiVDNWQ2E4TVpzZ2hKNHU4eHJNUnNFVkJ5c0JWUEg3UWZNRXBOWVMxSmMyalJwUjhzdUE9PQ==)
        CM_KEY_ALIAS_USERNAME: Encrypted(Z0FBQUFBQmV0Qkg4M2VJUVloWFNuNXRpU3huMV95UnRnWkVCaXBOSU85SGpMM2F3OEVFQy1TZ2dHaHpEOVRYRFFybFFXUGVibm1HWEJjMGxSUjRHekdqNFNPMjVmeUJyWWc9PQ==)
      flutter: stable
      xcode: latest
      cocoapods: default
    cache:
      cache_paths:
        - $FCI_BUILD_DIR/build
    triggering:
      events:
        - push
        - pull_request
      branch_patterns:
        - pattern: 'develop'
          include: true
          source: true
    scripts:
      - |
        # set up debug key.properties
        rm -f ~/.android/debug.keystore
        keytool -genkeypair \
        -alias androiddebugkey \
        -keypass android \
        -keystore ~/.android/debug.keystore \
        -storepass android \
        -dname 'CN=Android Debug,O=Android,C=US' \
        -keyalg 'RSA' \
        -keysize 2048 \
        -validity 10000
      - |
        # set up local properties
        echo "flutter.sdk=$HOME/programs/flutter" > "$FCI_BUILD_DIR/android/local.properties"
      - flutter packages pub get
      - flutter test
      - flutter build apk --split-per-abi
      - flutter build appbundle --release
      - |
        # generate signed universal apk with user specified keys
        universal-apk generate \
          --ks /tmp/keystore.keystore \
          --ks-pass $CM_KEYSTORE_PASSWORD \
          --ks-key-alias $CM_KEY_ALIAS_USERNAME \
          --key-pass $CM_KEY_ALIAS_PASSWORD \
          --pattern 'build/**/outputs/**/*.aab'
      - find . -name "Podfile" -execdir pod install \;
      - flutter build ios --release --no-codesign
    artifacts:
      - build/**/outputs/**/*.apk
      - build/**/outputs/**/*.aab
      - build/**/outputs/**/mapping.txt
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      slack:
        channel: '#flutter_build'
        notify_on_build_start: true
      email:
        recipients:
          - ezeugwagerrard@gmail.com

stable-workflow:
  <<: *baseline
    environment:
      flutter: beta